# Generated by Django 4.2.15 on 2024-08-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ssesion_key',
            new_name='session_key',
        ),
    ]
