# Generated by Django 4.2.15 on 2024-09-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_ssesion_key_cart_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
