# Generated by Django 4.2.15 on 2024-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_delivery_address_order_delivery_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_floor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
