# Generated by Django 4.2.15 on 2024-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_for_delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_city', models.TextField(blank=True, null=True)),
                ('delivery_street_house', models.TextField(blank=True, null=True)),
                ('delivery_apartment', models.TextField(blank=True, null=True)),
                ('delivery_door', models.TextField(blank=True, null=True)),
                ('delivery_floor', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_apartment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_door',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_floor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_street_house',
        ),
    ]
