# Generated by Django 4.2.15 on 2024-10-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_address_for_delivery_remove_order_delivery_apartment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address_for_delivery',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelTable(
            name='address_for_delivery',
            table='address_for_delivery',
        ),
    ]
