# Generated by Django 4.2.15 on 2024-10-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_address_for_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_for_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.address_for_delivery'),
        ),
    ]
